### ISSUE TITLE
Allow adding simply the file's directory to workspace

### ISSUE THREAD

**Issue by VulumeCode** [haifengkao/AlwaysOpenWorkspace#5]
I tried to add a root folder pattern to open the file's own directory, as a last resort for when it's not part of a project. 

I got close by using the pattern "./", but that opens the folder above.

**Comment by haifengkao** [comment]
I see. I will add another option. 
Personally I don't like to open all folders automatically, because VSCode will be painfully slow if the home directory is opened.

**Comment by VulumeCode** [comment]
It depends on the use case. For my work it would be very nice. At home not so much. 

VSCode is super fast though. I also tried "/" as a pattern, but that adds the disc root (like C:) to the workspace. Definitely not what I wanted but it still worked fine. Not a single stutter.

**Comment by haifengkao** [comment]
done 739bd101d20cf09975ff9ec232132eb4a689f32b
